config/routes.rb
Rails.application.routes.draw do
  resources :lists do
    resources :tasks, only: [:new, :create, :destroy] do
      get "done", on: :member
    end
  end

  devise_for :users

  root 'lists#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
    user ||= User.new # guest user (not logged in)
    can :manage, List, user_id: user.id
    can :manage, Task, list: {user_id: user.id}
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  has_many :tasks, dependent: :destroy
  belongs_to :user
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :list
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :lists
  has_many :tasks
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource :list

  # GET /lists
  # GET /lists.json
  def index
    @lists = current_user.lists
  end

  # GET /lists/new
  def new
    @list = List.new
    @list.user = current_user
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)
    @list.user = current_user

    respond_to do |format|
      if @list.save
        format.html { redirect_to lists_url, notice: 'List was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to lists_url, notice: 'List was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:name)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy, :done]
  before_action :authenticate_user!
  load_and_authorize_resource :list
  load_and_authorize_resource :task, :through => :list

  # GET /tasks/new
  def new
    @task = Task.new
    @task.list = @list
    @task.user = current_user
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    @task.list = @list
    @task.user = current_user

    respond_to do |format|
      if @task.save
        format.html { redirect_to lists_url, notice: 'Task was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'Task was successfully destroyed.' }
    end
  end

  def done
    @task.done = @task.done ? false : true
    @task.save!

    respond_to do |format|
      format.html {redirect_to lists_url}
      format.js
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
      @list = List.find(params[:list_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:title, :done, :list_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTasks</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_for(list) do |f| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<p id="notice"><%= notice %></p>

<%= t('welcome_html', username: current_user.email) %>

<h1><%= t List.model_name.human %> </h1>

<%= link_to 'New List', new_list_path %>

<br>

<% @lists.each do |list| %>
  <h2><%= list.name %> <%= link_to "[+]", new_list_task_path(list) %>
                       <%= link_to '[Edit]', edit_list_path(list) %>
                       <%= link_to '[X]', list, method: :delete, data: { confirm: 'Are you sure?' } %></h2>
  <% if list.tasks.empty? %>
    <%= "Nenhuma tarefa.".html_safe  %>
  <% else %>
    <table>
      <thead>
        <tr>
          <th>Task</th>
          <th colspan="2"></th>
        </tr>
      </thead>

      <tbody>
        <%= render list.tasks %>
      </tbody>
    </table>
  <% end %>
<% end %>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @list.name %>
</p>

<%= link_to 'Edit', edit_list_path(@list) %> |
<%= link_to 'Back', lists_path %>

app/views/tasks/_form.html.erb
<%= form_for([task.list,task]) do |f| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :list_id %>
    <%= f.text_field :list_id, value: task.list.name, disabled: true %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<tr data-taks-id="<%= task.id %>">
  <td>
    <% if task.done? %>
      <del><%= task.title %></del>
    <% else %>
      <%= task.title %>
    <% end %>
  </td>
  <td>
    <td><%= link_to (task.done? ? 'Undone!' : 'Done!'), done_list_task_path(task.list,task), remote: true %></td>
    <td><%= link_to '[X]', [task.list,task], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </td>
</tr>

app/views/tasks/done.js.erb
$("tr[data-taks-id=<%= @task.id %>]").replaceWith("<%= escape_javascript(render @task) %>");

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', lists_path %>